using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerControlArea : MonoBehaviour
{
    //playerï¿½ï¿½ï¿½Ú“ï¿½ï¿½Å‚ï¿½ï¿½ï¿½Xï¿½ï¿½Yï¿½Ìï¿½ï¿½
    public GameObject mainCamera;
    
    // Start is called before the first frame update
    void Start()
    {
        //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‹ï¿½ï¿½ï¿½ï¿½É‘Î‰ï¿½ï¿½ï¿½ï¿½Ä“ï¿½ï¿½ï¿½ï¿½ï¿½ÍˆÍ‚ï¿½ÏX
        GlovalValue.xLimit = (-mainCamera.transform.position.z * 1.12f);
        GlovalValue.yLimit = (-mainCamera.transform.position.z * 0.55f);
        //Debug.Log(xLimit);
        //Debug.Log(yLimit);
    }

    // Update is called once per frame
    void Update()
    {
        //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½İ‚ÌˆÊ’uï¿½ï¿½ï¿½æ“¾
        Vector3 cameraPos = mainCamera.transform.position;
        //ï¿½ï¿½ï¿½İ‚Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌˆÊ’uï¿½ï¿½ï¿½æ“¾
        Vector3 currentPos = transform.position;

        //Mathf.Clampï¿½ï¿½X,Yï¿½Ì’lï¿½ï¿½ï¿½ê‚¼ï¿½ê‚ªï¿½Åï¿½ï¿½`ï¿½Å‘ï¿½Ì”ÍˆÍ“ï¿½ï¿½Éï¿½ï¿½ß‚ï¿½B
        //ï¿½ÍˆÍ‚ğ’´‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ÍˆÍ“ï¿½ï¿½Ì’lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        currentPos.x = Mathf.Clamp(currentPos.x, -GlovalValue.xLimit + cameraPos.x, GlovalValue.xLimit + cameraPos.x);
        currentPos.y = Mathf.Clamp(currentPos.y, -GlovalValue.yLimit + cameraPos.y, GlovalValue.yLimit + cameraPos.y);

        //ï¿½Ç‰ï¿½ï¿½@positionï¿½ï¿½currentPosï¿½É‚ï¿½ï¿½ï¿½
        transform.position = currentPos;
    }
}
